### ISSUE TITLE
Why does it has symbol ids and is it optional?

### ISSUE THREAD

**Issue by anselmh** [matthewwithanm/react-inlinesvg#11]
Hi,

just tried to use the lib and figured that each symbol ID is being hashed (initial: `#add`, through lib: `#add___974976503`). Why is that and can I disable it? Couldn’t find anything in the documentation.

Thanks for help.

**Comment by matthewwithanm** [comment]
Hi! This technique embeds SVGs directly into the host document, so if you have two SVGs with the same ID, they're going to end up in the same namespace. Styles applied in one document will actually be applied to both!

You can disable it with the `uniquifyIDs` prop: just pass it `false`.

**Comment by anselmh** [comment]
Thanks! Can you add this to the README to avoid further questions on that?

**Comment by matthewwithanm** [comment]
Definitely. I'm out of town right now so it might be a little while. Then again…that "Merge PR" button is pretty easy, even from my phone (;

**Comment by anselmh** [comment]
Hey, I had a chance to try it out now but adding the prop had no effect on the hashing which still happens. My code looks like this:

    <Isvg src="src/to/my.svg" className="svgsprite" uniquifyIDs="false" />

According to you this should work, right? I also tried `0` instead of `false` but this had no effect as well. Is it perhaps because [this if statement isn’t correct in here](https://github.com/matthewwithanm/react-inlinesvg/blob/master/src/index.coffee#L208) (not entirely sure if it is)?

**Comment by anselmh** [comment]
My fault: Need to set it via `uniquifyIDs={false}`. I’ll see if I can do a PR later for adding the documentation.
