### ISSUE TITLE
Icon coloring conflicts

### ISSUE THREAD

**Issue by axertion** [matthewwithanm/react-inlinesvg#17]
When embedding multiple SVGs using react-inline svg, their are color conflicts because of the style class names contained within the `<svg>` tag:

Example of issue:
![color clash](http://i.imgur.com/NpBTK2k.png)

As you can see, the bottom icon colors are being applied to the top icons, and vice versa.

The correct colors should look like this:

![color correct](http://i.imgur.com/8S5LzdZ.png)

What I believe is happening is that the styles from one SVG are the same as another.

![conflicting styles](http://i.imgur.com/nsVkjr3.png)

Is there a way for react-inlinesvg to parse out the SVG styles and apply a unique key to them to they do not conflict?

**Comment by jkarttunen** [comment]
I think I'm encountering similar issues with gradients. Have you tried exporting in SVG format with no style classes? (Not user if you can do this, but some of the AI  style formats seem to work better at least for me.

**Comment by matthewwithanm** [comment]
@axertion I imagine that we could have a `classPrefix` prop, but this kind of parsing is usually error-prone.

**Comment by jkarttunen** [comment]
My issue was diffrent, probably caused by non-unique ID's in svg files repeated several times. using key= fixed it somehow.

**Comment by jkarttunen** [comment]
@axertion have you tried exporting CSS differently:
![screen shot 2015-09-02 at 17 44 34](https://cloud.githubusercontent.com/assets/914822/9634428/5e4a4760-519a-11e5-95ad-0e2a675cfc91.png)

**Comment by gilbarbara** [comment]
spring cleaning
