### ISSUE TITLE
Flickering / redraws.

### ISSUE THREAD

**Issue by jkarttunen** [matthewwithanm/react-inlinesvg#18]
I'm using rather big svg images, not icons with react-inlinesvg. 
There seems to be a lot of flickering and redraws when doing new routes / redraving parts of UI.
Somehow React seems to think it needs to redraw the svg elements a lot.

I have not yet investigated this yet, but I'll experiment with pure component mixins.

**Comment by matthewwithanm** [comment]
Off, yeah. We need to implement `shouldComponentUpdate`.

**Comment by gilbarbara** [comment]
Hey @matthewwithanm 

I'm having this problem too but appears that you aren't updating this repo anymore.
Are you accepting pull requests? new contributors?

I've been working a lot with svg [svgporn](https://github.com/gilbarbara/logos) and I'd love to help.

[s]

**Comment by gilbarbara** [comment]
Fixed f36492593d7009ade7d972f5dbd386991643ab54
