### ISSUE TITLE
Caching AJAX requests

### ISSUE THREAD

**Issue by operatino** [matthewwithanm/react-inlinesvg#25]
Hi,

Great thanks for the nice react module, I found it the best among other inline svg loading technics, especially for isomorphic apps. 

But I noticed one issue though, when using multiple SVG images on a page, there's a lot of identical requests for same images:

![image](http://d.pr/i/1Ngt+)

What do you think about adding memory cache for previously loaded SVG's? Since SVG's aren't heavy, it should not cause any problems with memory leaks.

**Comment by jayeszee** [comment]
+1

**Comment by LoicUV** [comment]
+1

**Comment by ifuller1** [comment]
Hey Guys. 

We had the same issue so added some caching support to a fork of the library: https://github.com/trailsuite/react-inlinesvg/

There's a significant different between our fork and this package so we haven't raised a PR. Our original approach was to make a small change to @matthewwithanm's excellent module but some missing dependencies and a lack of expertise in coffee script caused us to go the long way around. If @matthewwithanm is interested we'll happily raise a PR with just the caching changes but might need some assistance in building the existing library and in stubbing the http.get requests.

**Comment by lostpebble** [comment]
This is something I would really like to see in this package. Luckily they're all cached, so shouldn't affect the end user too much, but the fact that it makes a request each and every time is not great. For instance, I have a slider that rotates through a group of SVGs, one every second, and every single one makes a new request even if it's been displayed before.

**Comment by ifuller1** [comment]
@lostpebble - They're often uncached. If you have the same icon repeated on a page, as we do, then the browser initiates multiple xhrs'. The first request to fire is only available in the cache once several other requests have started with a cache miss. You're welcome to use https://github.com/trailsuite/react-inlinesvg/ if you like. Our tests are green on Travis - biggest TODO is fixing the linting.

**Comment by lostpebble** [comment]
Thanks. I've just tried your fork, but it doesn't seem to solve the problem. I'll create an issue in that repository.

**Comment by ifuller1** [comment]
@lostpebble Did you see the config? Caching isn't on by default so you need to enable it (see the Readme.md). I'll enable issues on the repo too.

**Comment by lostpebble** [comment]
Ah okay, I see. Sorry, just assumed the Readme.md was exactly the same from the fork. It is working now.

**Comment by gilbarbara** [comment]
hey @ifuller1 
I've refactored the source code to ES2015 and if you like to contribute the cache option back in, it will be great.

**Comment by ifuller1** [comment]
Thanks @gilbarbara - totally missed this email. Will come back to it ASAP.

**Comment by ifuller1** [comment]
Hi @gilbarbara - PR raised https://github.com/matthewwithanm/react-inlinesvg/pull/32

Comments welcome.

**Comment by export-mike** [comment]
Is this now considered closed? what was the reasoning to make cacheGetRequests default to false?

**Comment by ifuller1** [comment]
It would be good for somebody to independently validate this but yes, I think it is.

Defaulting to false as not to cause unexpected behaviour for existing users.

**Comment by export-mike** [comment]
@ifuller1 I'll take a look at the code and get back to you :)

**Comment by ifuller1** [comment]
Thanks @export-mike, it's more about validating it works in production (we're using it successfully already - but would welcome validation from some of the authors)
