### ISSUE TITLE
Spatial Indexing

### ISSUE THREAD

**Issue by iSamuelBarney** [matthewwithanm/react-inlinesvg#28]
Using this on an app I'm building wrote a few lines to get grid item order 0-9+ based on x&y and another that generates x&y as well as order if it has none number of columns doesn't matter it can handle it... Is this something I should share here or would anyone want this feature?

**Comment by gilbarbara** [comment]
hey @samuelbarney 
Do you have a public example or could share a screenshot?

**Comment by samuelbarney** [comment]
I'd have to change it before showing it, FYI I wrote it for 1width gridtiles forgot to mention that so if your using resize=true then it will need to be modified to store width or something. I'll post the whole example sometime tomorrow when I get time. The basic equation was like o=(y * c) + x where o is numeric order and c is number of columns so adding width is prob not something I have time to figure out but anyway I'll post it hopefully someone gets as much use out of it as I did.
