### ISSUE TITLE
"TypeError: Invalid URL" when mounting components with Enzyme in tests

### ISSUE THREAD

**Issue by chapati23** [matthewwithanm/react-inlinesvg#29]
This works fine in development but breaks in my tests:
```jsx
<Isvg src={"/assets/img/utilities/" + grid.utility.name.toLowerCase() + ".svg"} />
```

I suspect Mocha or Enzyme set some different root-paths in their test-environment where the component gets mounted which leads to all my tests that contain `<Isvg>` components breaking.

Any idea for a workaround that doesn't involve me wrapping <Isvg> in a `env.test ? <Isvg path=""> : <Isvg path="/normal/path/to/my.svg" />`

**Comment by gilbarbara** [comment]
hey,
Can you post an error log?
Isvg loads the files with httpplease (xmlhttprequest). You could mock it or you can create a simple server with your assets for testing.

**Comment by chapati23** [comment]
can't reproduce atm because my testsetup changed. but it'd be cool to add a little paragraph to the README or wiki with this information. how to mock Isvg in tests or at least that it uses httpplease (you could find out by digging through the code but that can take a lot of time)

and btw: thanks for this package :)

**Comment by gilbarbara** [comment]
Added httpplease to README.
Thanks

**Comment by chapati23** [comment]
Thanks :)
