### ISSUE TITLE
Browser request for fallback img even when not needed.

### ISSUE THREAD

**Issue by jamesslock** [matthewwithanm/react-inlinesvg#30]
Right now it appears that the browser will make two requests one for the .svg and another for the .png if the svg is able to load the browser should not also request the png.

**Comment by gilbarbara** [comment]
Hey, which version are you using? I just tried with 0.5.0 and it didn't load the fallback png.

**Comment by jamesslock** [comment]
I'm using the latest version, how ever I am using this on an Isomorphic app.
