### ISSUE TITLE
Support for Server-side Rendering

### ISSUE THREAD

**Issue by MarkRabey** [matthewwithanm/react-inlinesvg#33]
The component returns false for `supportsInlineSVG()` and `isSupportedEnvironment()` when rendering server-side. This results in `.unsupported` being added to the wrapper, rather than `.loaded`. And the SVG is not loaded until the client is able to render it. This also causes an error in my browser console because the client and server are not rendering the same code.

Can something be done to support server-side?

**Comment by djskinner-sky** [comment]
I wonder if this could be addressed by adding the additional class names on `componentDidMount` rather than `componentWillMount`. That way they will only get added on the client and the initial diff should be the same. Can anyone see any obvious issues with this approach?

**Comment by gilbarbara** [comment]
Merged
