### ISSUE TITLE
Component appears to render siblings when src doesn't exist

### ISSUE THREAD

**Issue by iamchristopher** [matthewwithanm/react-inlinesvg#34]
When rendering an instance of `<Svg>` using a resource that doesn't exist, it seems to render its siblings as well as the provided fallback elements.

Example:

```
<footer>
    <Svg src="/images/this-does-not-exist.svg">
        <img src="/images/this-is-a-fallback.png"/>
    </Svg>
    <p>Some text.</p>
</footer>
```

Results in:

```
<footer>
    <img src="/images/this-is-a-fallback.png"/>
    <p>Some text.</p>
    <p>Some text.</p> <!-- Duplicated markup -->
</footer>
```
Currently using v0.5.3.

**Comment by gilbarbara** [comment]
Hey,
I couldn't reproduce this behaviour in a clean `create-react-app` setup.

However the `create-react-app` uses a proxy for the dev-server and it won't return a 404 when the file doesn't exist, instead it returns 200 and the index.html content. Thus preventing this component to load the fallback.
