### ISSUE TITLE
production build renders an iframe like component?

### ISSUE THREAD

**Issue by SkateFreak** [matthewwithanm/react-inlinesvg#36]
`<span class="isvg loaded">
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700" rel="stylesheet" type="text/css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="/main.css" rel="stylesheet" type="text/css">
	<title>ContactsUI</title>
	<div id="root___0"></div>
	<script src="/main.js"></script>
</span>`

this is what i get when i use react-inlinesvg on production build.
any clue why is it happening?

**Comment by gilbarbara** [comment]
It looks like you are loading your html file ou something. Check your svg source markup?
I use this package in production in several projects and I never had any problems.

**Comment by gilbarbara** [comment]
Also check the path of you svg file.
I just tried to load a SVG that didn't exist and the server returned the index.html content instead of a 404 response.
