### ISSUE TITLE
babel-plugin-add-module-exports to dependencies?

### ISSUE THREAD

**Issue by marthakelly** [matthewwithanm/react-inlinesvg#38]
hey there, should we move babel-plugin-add-module-exports to dependencies, instead of dev dependencies? 

it seems like the babelrc is using it in prod: https://github.com/matthewwithanm/react-inlinesvg/blob/55ada4616274eac0693086fcfbba3e844b1cc9d5/.babelrc#L10

**Comment by marthakelly** [comment]
I'm happy to make a PR if you're cool with the change

**Comment by gilbarbara** [comment]
Hey @marthakelly 
Babel is only used to build the package and transpile the source before publishing to the npm registry. It's not needed to run when required.

👍
