### ISSUE TITLE
How can I update SVG parameters?

### ISSUE THREAD

**Issue by pentool** [matthewwithanm/react-inlinesvg#39]
Hello,

Pardon my overly simplistic question but still a newbie at doing react stuff. I want to be able to update SVG parameters (eg change fill color) when I tap on the SVG image. It's really easy to accomplish this in regular HTML/CSS but in react it gives me a headache.

The SVG file is loading just fine and I can click on it and the click event is received. But when I try to toggle the class of an SVG element that doesn't seem to work. I think it might somehow has to do with how react updates the dom - but I'm not entirely sure.

`onClickStrength() {
        $('#strength1 .circle').toggleClass('selected');
    }`

Above is my click event handler. I'm trying to use jquery to match an element inside the SVG and toggle it's class. I suspect I can't even use jquery inside a react component because react works completely differently.

Could someone help me out how to do this?

Thanks.

**Comment by gilbarbara** [comment]
Hello.

React renders plain html to the DOM. It uses a virtual DOM to compare changes and only update what really change on a re-render but the content on the page it's pretty much standard stuff.

Did you really have a `circle (SVGCircleElement)` with a class `.circle`? Have you explicitly added a class to it and made sure that it still have this class when it is rendered on the DOM? You can inspect the inline SVG code with devtools to make sure it has the characteristics that you trying to query.
