### ISSUE TITLE
hashed IDs

### ISSUE THREAD

**Issue by mikeriley131** [matthewwithanm/react-inlinesvg#44]
I'm seeing this issue where the `<id>`s in my SVG mark-up are getting hashed, but the reference to that `<id>` in the `<style>` element is not, which is causing the image to break when using `clipPath`. Are these hashes necessary? Is it just for cache-busting? Can that be turned off as an option?

```
<style type="text/css">
	.logo-circle-left{fill:#ffffff;}
	.logo-circle-left-lines{fill:#ffffff;clip-path:url(#clip-1);}
	.logo-circle-right{fill:#ffffff;}
	.logo-circle-right-lines{fill:#ffffff;clip-path:url(#clip-2);}
	.logo-lines{fill:none;stroke:#ffffff;stroke-width:3;stroke-miterlimit:10;}
	.logo-star{fill:#000000;}
	.logo-text{fill:#ffffff;}
	.logo-bg-join{fill:#ffffff;}
</style>
```

```
<g>
	<defs>
		<circle id="SVGID_3____-341823852" cx="822.5" cy="384.4" r="384.4"></circle>
	</defs>
	<clipPath id="clip-2___-341823852">
		<use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#SVGID_3____-341823852" style="overflow:visible;"></use>
	</clipPath>
        ...
<g>
```

Thanks.

**Comment by matthewwithanm** [comment]
Hi @mikeriley131! No it's not for cache busting, it's to guard against weirdness that comes from having two elements with the same id on the page (e.g. the wrong one being used as a mask). You can disable it with a prop; see the README.

**Comment by mikeriley131** [comment]
Ah, I completely missed that in the README. Sorry about that. Thanks for the reply.
