### ISSUE TITLE
svg is not updating if the src change dynamically

### ISSUE THREAD

**Issue by AvraamMavridis** [matthewwithanm/react-inlinesvg#48]
There are cases where the src comes from the props of a component dynamically and changes dynamically, in my case: 

```
class Button extends Component {

   //..

  getIconPath() {
    if (!this.props.iconName) return null;

    const { iconBasePath } = App.cfg;
    const split = this.props.iconName.split('.');
    const name = split[0];
    const extension = split[1] || 'svg';
    return `${ iconBasePath + name }.${ extension }`;
  }

  render() {
    // ...

    return (
        <button className={ buttonClass } onClick={ this.onClickHandler }>
          { this.getIconPath() ? <Isvg src={ this.getIconPath() } /> : '' }
          <div className="button__text">{ text }</div>
        </button>
    );
  }
}

export default Button;
```

The `Isvg` is not updating. (I am sure it doesnt has to do with my code because switching to ReactSVG solve the issue). I think it has to do with the `shouldComponentUpdate`

**Comment by blunatic** [comment]
I've had this issue before and solved it by updating the key of the <InlineSVG /> on each src change.

**Comment by gilbarbara** [comment]
Yeah, you should update the `key` props when the source changes.
