### ISSUE TITLE
Dynamic `src` attrbute.

### ISSUE THREAD

**Issue by wires** [matthewwithanm/react-inlinesvg#5]
Hi,

I thought it should be possible to change the `src` attribute and load a different file (or pull from cache).
I put together a little test demonstrating what I'm talking about, see https://github.com/wires/react-inlinesvg-test 

Look at [`index.js`](https://github.com/wires/react-inlinesvg-test/blob/master/index.js), this is where the "meat" is...

```js
var React = require("react");
var ISvg = require("react-inlinesvg");

var App = React.createClass({
    propTypes: {
        index: React.PropTypes.number.isRequired
    },
    render: function () {
        var FILES = ["test-a.svg", "test-b.svg"];
        var fn = FILES[this.props.index];
        console.log(fn)
        return (<ISvg src={ fn }/>);
    }
});

window.addEventListener('DOMContentLoaded', function(){
    setInterval(function(){
        var i = Math.floor(Math.random()*2); // 0 or 1
        React.render(
            <App index={i}/>
            , document.getElementById('content'));
    }, 500);
});
```

I ran into this when trying to use `react-inlinesvg` with `react-router`, it wouldn't change page.

Any thoughts?

**Comment by wires** [comment]
If you checkout the [`test/router` branch](https://github.com/wires/react-inlinesvg-test/tree/test/router) of the same repo, I've demonstrated the problem with `react-router`. (here is [`index.js`](https://github.com/wires/react-inlinesvg-test/blob/test/router/index.js))

Again, just run `gulp`, this starts a HTTP server on port 3003.

Load either `http://localhost:3003/#/page/test-b.svg` or `http://localhost:3003/#/page/test-a.svg` and you get the right image. However, clicking the links doesn't work. (Have a look at the JS console to see the redraws and the parameter is changing).

Maybe I'm using your software wrongly. :-)

**Comment by dubert** [comment]
If you add a key, it should work. React needs to know that it's a different image.

**Comment by captDaylight** [comment]
Yup, adding a key did it for me, thanks @dupert

**Comment by jkarttunen** [comment]
Adding a key helped partially. Linear gradients so not seem to get unique id, and this causes them to disappear from
icon If toggling same icon on and off somewhere else

**Comment by export-mike** [comment]
it would be helpful if this key was added to the component inside of react-inlinesvg

**Comment by export-mike** [comment]
I attempted at making a change but failed on esprima-six package not found, looks like this repo needs some love

**Comment by gilbarbara** [comment]
spring cleaning
