### ISSUE TITLE
No style prop

### ISSUE THREAD

**Issue by imdevan** [matthewwithanm/react-inlinesvg#52]
One big thing that I noticed was that this component does not have the ability to add a style object to it, like I can with every other react component. 

This can be done the same way that the className is added to the inner component. 

I imagine that the style would be added to the wrapper, but the svg also makes sense.

**Comment by imdevan** [comment]
Just saw that this is in pr! Can that be merged? It's been there since December.

**Comment by gilbarbara** [comment]
Added in 332b4a6579c898e478a3c27445276d01207be185
