### ISSUE TITLE
src-change won't trigger new request

### ISSUE THREAD

**Issue by lumio** [matthewwithanm/react-inlinesvg#55]
Hi 😀 

I just found out that changing the `src`-prop won't do anything, once the SVG got loaded.
The old inline SVG should be replaced as soon as the new one got loaded.

Right now I solved it by rendering two different `Isvg`s with two different keys.

**Comment by bryant988** [comment]
i solved this by setting the `key` prop on the `Isvg` tag to match the `src` prop. That way, whenever the `src` changes, they `key` changes, and it toggles the change

**Comment by bryant988** [comment]
`<Isvg  
  key={this.props.src}
  src={this.props.src}
  ...
/>`

**Comment by lumio** [comment]
@bryant988 that's what I meant with:
> Right now I solved it by rendering two different Isvgs with two different keys.

The problem with this: It flickers when changing the `src`. I would expect that the new SVG is rendered after it's being loaded

**Comment by gilbarbara** [comment]
@lumio You could use the `preloader` method, CSSTransitionGroup or something like it.
Transition those changes goes beyond the scope of this library.
