### ISSUE TITLE
React.PropTypes deprecation warnings

### ISSUE THREAD

**Issue by cw-mleparc** [matthewwithanm/react-inlinesvg#56]
As of React v15.5.0 any use of React.PropTypes throws a warning, which means any project using react-inlinesvg is getting these warnings as well even if they clean up their own usages of PropTypes. 

https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by davidsonfellipe** [comment]
@cw-mleparc PR created for it.

cc// @matthewwithanm
