### ISSUE TITLE
Warning: Accessing factories like React.DOM.span has been deprecated...

### ISSUE THREAD

**Issue by chrismllr** [matthewwithanm/react-inlinesvg#60]
**Versions:**
`react-dom: 15.6.1`
`react: 15.6.1`

**Full warning:**
```
Warning: Accessing factories like React.DOM.span has been deprecated and will be removed in v16.0+. Use the react-dom-factories package instead.  Version 1.0 provides a drop-in replacement. For more info, see https://fb.me/react-dom-factories
```

Triggered by line 283 in `index.js`
https://github.com/matthewwithanm/react-inlinesvg/blob/master/src/index.js#L283

Further reference:
https://github.com/facebook/react/tree/master/packages/react-dom-factories

**Comment by gilbarbara** [comment]
fixed in 0.6.1
