### ISSUE TITLE
Stopped working after upgrading my project to React 16

### ISSUE THREAD

**Issue by GasimGasimzada** [matthewwithanm/react-inlinesvg#67]
> TypeError: this.updater.enqueueCallback is not a function. (In 'this.updater.enqueueCallback(this, callback, 'setState')', 'this.updater.enqueueCallback' is undefined)

I don't know what the problem is but I think it has something to with React version mismatch between 15.6 and 16.

**Comment by gilbarbara** [comment]
Are you the standalone version?

**Comment by GasimGasimzada** [comment]
What do you mean? It is the version installed as mentioned in Github page. If there has been an update, I will check it out.
